quarkus.http.port=81
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:3002,http://127.0.0.1:3002,http://localhost:5173,http://127.0.0.1:5173
quarkus.http.cors.methods=GET,POST,OPTIONS
quarkus.http.cors.headers=Accept,Content-Type

quarkus.datasource.db-kind=h2
quarkus.datasource.username=sa
quarkus.datasource.password=sa
quarkus.datasource.jdbc.url=jdbc:h2:mem:process-engine;DB_CLOSE_DELAY=-1

quarkus.cibseven.generic-config.history=full
quarkus.cibseven.generic-config.database-schema-update=true
quarkus.cibseven.job-executor.thread-pool.max-pool-size=5

# Kubernetes configuration
quarkus.container-image.build=true
quarkus.container-image.push=false
quarkus.container-image.group=cibseven
quarkus.container-image.name=quarkus-motor-example
quarkus.container-image.tag=latest

quarkus.kubernetes.image-pull-policy=Never
quarkus.kubernetes.deploy=true

# Kubernetes service port configuration
quarkus.kubernetes.ports.http.container-port=81
quarkus.kubernetes.ports.http.host-port=81

# Add namespace configuration
quarkus.kubernetes.namespace=default

# Optional: Configure service type
#quarkus.kubernetes.service-type=LoadBalancer
# Optional: Configure replicas
#quarkus.kubernetes.replicas=1
